spring.application.name=jobtracker

server.port=1512

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/jobtracking
spring.datasource.username=root
spring.datasource.password=root@1503

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false